#!/bin/sh

RESP=$(/opt/homebrew/bin/mop init --config /opt/homebrew/etc/mop/mop.yaml 2>&1)
case "$RESP" in
    Error*)
        echo "
Enabled clef-signer but clef is not running.
Check https://redesblock.github.io/mop/#/for more info.
After you fix configuration run 'mop-get-addr' again.
        "
        ;;
    *)
        BNB_ADDRESS=$(echo "$RESP" | grep ethereum | cut -d' ' -f6 | tr -d '"')
        echo "
Please make sure there is BNB and, if required, MOP available on the following Ethereum address on BNB Smart Chain: 0x$BNB_ADDRESS.

Learn how to fund your node by visiting our docs at https://redesblock.github.io/mop/#/installation/fund-your-node

Once your node's wallet has received the funds start service with 'brew services start mop' and it will begin joining the MOP network.

See the docs for more information at https://redesblock.github.io/mop/#/.
        "
        ;;
esac
